# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5254c3bb817335a3fe3d768adfbe117d707b09feceec2bdf15d36e901a5492cd1da7227712fbdfaaa9c2568ba3a80d6cde46bb74c3ce948b6c078de307748e44

test:
  secret_key_base: 4e649b866f1b44a7af5f39bee7a40f9d0d5c6b41ac3b95b928699dca51bed2001203d87754c8cca8a1cabd5e5df345b70607f2fa508af0c3d8ae72bac88aa591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
